namespace claims.src.gui.playerGui
{
    /// <summary>
    /// Which form the secondary window next to the main dialog is currently showing.
    /// NONE means the window is closed.
    /// </summary>
    public enum EnumUpperWindowSelectedState
    {
        NONE, NEED_NAME, NEED_AGREE, INVITE_TO_CITY_NEED_NAME, KICK_FROM_CITY_NEED_NAME, UNINVITE_TO_CITY,
        CLAIM_CITY_PLOT_CONFIRM, UNCLAIM_CITY_PLOT_CONFIRM, PLOT_PERMISSIONS, ADD_FRIEND_NEED_NAME, REMOVE_FRIEND,
        PLOT_SET_PRICE_NEED_NUMBER, PLOT_SET_TAX, PLOT_SET_TYPE, PLOT_SET_NAME, PLOT_CLAIM, PLOT_UNCLAIM,
        LEAVE_CITY_CONFIRM,
        CITY_RANK_REMOVE_CONFIRM, CITY_RANK_ADD, SELECT_NEW_CITY_NAME, ADD_CRIMINAL_NEED_NAME, REMOVE_CRIMINAL,
        CITY_PRISON_REMOVE_CELL_CONFIRM, CITY_SUMMON_NEED_NAME, ADD_PLOTSGROUP_MEMBER_NEED_NAME, REMOVE_PLOTSGROUP_MEMBER_SELECT,
        REMOVE_PLOTSGROUP_MEMBER_CONFIRM,
        CITY_PLOTSGROUP_PERMISSIONS, CITY_PLOTSGROUP_PLOT_CLAIM_CONFIRM, CITY_PLOTSGROUP_PLOT_UNCLAIM_CONFIRM,
        CITY_PLOTSGROUP_ADD_NEW_NEED_NAME, CITY_PLOTSGROUP_REMOVE_SELECT, CITY_PLOTSGROUP_REMOVE_CONFIRM,

        SELECT_NEW_ALLIANCE_NAME, INVITE_TO_ALLIANCE_NEED_NAME, KICK_FROM_ALLIANCE_NEED_NAME,
        LEAVE_ALLIANCE_CONFIRM, NEW_ALLIANCE_NEED_NAME, ALLIANCE_PREFIX_NEED_NAME, ALLIANCE_SEND_NEW_CONFLICT_LETTER_NEED_NAME,
        ALLIANCE_SEND_PEACE_OFFER_CONFIRM,
        CITY_PLOTS_PERMISSIONS, CITY_RANK_DELETE_CONFIRM, CITY_RANK_CREATION_NEED_NAME,

        // Treasury.
        CITY_SET_FEE, CITY_WITHDRAW, CITY_DEPOSIT_CONFIRM,

        // Diplomacy: unions, non-aggression pacts, city-level war declarations, ultimatums.
        ALLIANCE_SEND_NEW_UNION_LETTER_NEED_NAME, ALLIANCE_CANCEL_UNION_SELECT,
        CITY_SEND_NEW_CONFLICT_LETTER_NEED_NAME, CITY_SEND_NAP_OFFER_NEED_NAME, ALLIANCE_SEND_NAP_OFFER_NEED_NAME,
        SEND_ULTIMATUM,

        // Villages.
        NEW_VILLAGE_NEED_NAME, VILLAGE_ABANDON_CONFIRM, VILLAGE_UPGRADE_CONFIRM
    }
}
