using claims.src.rights;
using Vintagestory.API.Common;
using Vintagestory.API.Common.CommandAbbr;
using Vintagestory.API.Config;
using Vintagestory.API.Server;

namespace claims.src.commands.register
{
    public class ServerCommands
    {   
        public static void RegisterCommands(ICoreServerAPI sapi)
        {
            var parsers = sapi.ChatCommands.Parsers;

            RegisterCityCommands(parsers, sapi);
            RegisterCitizenCommands(parsers, sapi);
            RegisterPlotCommands(parsers, sapi);
            RegisterCAdminCommands(parsers, sapi);
            RegisterAllianceCommands(parsers, sapi);

            sapi.ChatCommands.Create("cc").HandleWith(commands.ClaimsChatCommands.onCommandCC)
             .RequiresPlayer().RequiresPrivilege(Privilege.chat);

            sapi.ChatCommands.Create("lc").HandleWith(commands.ClaimsChatCommands.onCommandLC)
             .RequiresPlayer().RequiresPrivilege(Privilege.chat);

            sapi.ChatCommands.Create("gc").HandleWith(commands.ClaimsChatCommands.onCommandGC)
              .RequiresPlayer().RequiresPrivilege(Privilege.chat);

            sapi.ChatCommands.Create("agree").HandleWith(commands.agreementCommand.onCommand)
              .RequiresPlayer().RequiresPrivilege(Privilege.chat);

            sapi.ChatCommands.Create("accept").HandleWith(commands.AcceptCommand.onCommand)
              .RequiresPlayer().RequiresPrivilege(Privilege.chat)
              .WithArgs(parsers.OptionalWord("cityName"));

            sapi.ChatCommands.Create("deny").HandleWith(commands.DenyCommand.onCommand)
              .RequiresPlayer().RequiresPrivilege(Privilege.chat)
              .WithArgs(parsers.OptionalWord("cityName"));

            sapi.ChatCommands.Create("plotsgroupaccept").HandleWith(commands.AcceptCommand.onAcceptPlotGroup)
              .RequiresPlayer().RequiresPrivilege(Privilege.chat)
              .WithArgs(parsers.Word("cityName"), parsers.Word("groupName"));

            sapi.ChatCommands.Create("plotsgroupdeny").HandleWith(commands.AcceptCommand.onDenyPlotGroup)
              .RequiresPlayer().RequiresPrivilege(Privilege.chat)
              .WithArgs(parsers.Word("cityName"), parsers.Word("groupName"));

            sapi.ChatCommands.Create("plotsgroupleave").HandleWith(commands.AcceptCommand.onLeavePlotGroup)
              .RequiresPlayer().RequiresPrivilege(Privilege.chat)
              .WithArgs(parsers.Word("cityName"), parsers.Word("groupName"));
        }
        public static void RegisterCityCommands(CommandArgumentParsers parsers, ICoreServerAPI sapi)
        {
            sapi.ChatCommands.Create("city")
                .RequiresPlayer().RequiresPrivilege(Privilege.chat).WithAlias("c")
                    /////////
                     .BeginSub("create")
                        .HandleWith(commands.CityCommand.CreateNewCity)
                        .WithAlias("new")
                        .WithDesc("Create a new city.")
                        .WithArgs(parsers.Word("cityName"))
                     .EndSub()
                     /////////
                     .BeginSub("delete")
                        .HandleWith(commands.CityCommand.DeleteCity)
                        .WithDesc("Remove the city.")
                     .EndSub()
                      .BeginSub("inviteaccept")
                        .HandleWith(commands.AcceptCommand.AcceptToAllianceInvitation)
                        .WithDesc("Accept invitation to an alliance.")
                        .WithArgs(parsers.Word("allianceName"))
                     .EndSub()
                    /////////
                    .BeginSub("claim")
                        .WithDesc("Claim new plot for the city.")
                        .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_CLAIM_PLOT))
                        .HandleWith(commands.CityCommand.ClaimCityPlot)
                    .EndSub()
                    /////////
                    .BeginSub("unclaim")
                         .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_UNCLAIM_PLOT))
                        .WithDesc("Unclaim city's plot.")
                        .HandleWith(commands.CityCommand.UnclaimCityPlot)
                    .EndSub()                  
                    /////////
                    .BeginSub("extraplot")
                        .WithDesc("Buy an extra plot.")
                        .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_BUY_EXTRA_PLOT))
                        .HandleWith(commands.CityCommand.ProcessExtraPlot)
                    .EndSub()
                    /////////
                    .BeginSub("outpost")
                        .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_BUY_OUTPOST))
                        .HandleWith(commands.CityCommand.ClaimOutpost)
                        .WithDesc("Buy outpost.")
                    .EndSub()
                    /////////
                    .BeginSub("here")
                        .WithDesc("Show info about city on this plot.")
                        .HandleWith(commands.CityCommand.CityHere)
                    .EndSub()
                    /////////
                    .BeginSub("info")
                        .WithDesc("Show info about city.")
                        .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_INFO))
                        .HandleWith(commands.CityCommand.CityInfo)
                        .WithArgs(parsers.Word("cityName"))
                    .EndSub()
                    /////////
                    .BeginSub("invite")
                        .WithDesc("Invite a player to the city.")
                        .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_INVITE))
                        .WithArgs(parsers.Word("playerName"))
                        .HandleWith(commands.CityCommand.InviteToCity)
                    .EndSub()
                    /////////
                    .BeginSub("kick")
                        .HandleWith(commands.CityCommand.CityKick)
                         .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_KICK))
                        .WithDesc("Kick a player from the city.")
                        .WithArgs(parsers.Word("playerName"))
                    .EndSub()
                    /////////
                    .BeginSub("leave")
                         .WithDesc("Leave the city.")
                         .HandleWith(CityCommand.CityLeave)
                     .EndSub()
                      ////////
                      .BeginSub("uninvite")
                         .WithDesc("Delete invitation for player.")
                         .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_UNINVITE))
                         .WithArgs(parsers.Word("playerName"))
                         .HandleWith(commands.CityCommand.UninviteToCity)
                     .EndSub()
                     ////////
                     .BeginSub("list")
                         .WithDesc("List all cities.")
                         .HandleWith(commands.CityCommand.ProcessListCities)
                     .EndSub()
                     /////////
                     .BeginSub("set")
                         .WithDesc("Setters for city.")
                             .BeginSub("permissions")
                                 .WithDesc("Change city permissions.")
                                 .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_SET_PLOT_ACCESS_PERMISSIONS))
                                 .WithAlias("p")
                                 .HandleWith(commands.CityCommand.CitySetPermissions)
                                 .IgnoreAdditionalArgs()
                             .EndSub()
                             .BeginSub("info")
                                 .WithDesc("City info of setters.")
                                 .HandleWith(commands.CityCommand.CitySetInfo)
                             .EndSub()
                             .BeginSub("name")
                                 .WithDesc("Set city name.")
                                 .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_SET_NAME, EnumPlayerPermissions.CITY_SET_ALL))
                                 .WithArgs(parsers.Word("cityName"))
                                 .HandleWith(commands.CityCommand.SetCityName)
                             .EndSub()
                             .BeginSub("open")
                                 .WithDesc("Set city open/close.")
                                 .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_SET_OPEN_STATE, EnumPlayerPermissions.CITY_SET_ALL))
                                 .WithArgs(parsers.WordRange("state", "on", "off"))
                                 .HandleWith(commands.CityCommand.CitySetOpen)
                             .EndSub()
                             .BeginSub("fee")
                                 .WithDesc("Set city fee.")
                                 .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_SET_GLOBAL_FEE, EnumPlayerPermissions.CITY_SET_ALL))
                                 .WithArgs(parsers.Int("fee"))
                                 .HandleWith(commands.CityCommand.CitySetFee)
                             .EndSub()
                             .BeginSub("mayor")
                                 .WithDesc("Set city mayor")
                                 .WithArgs(parsers.Word("newMayorName"))
                                 .HandleWith(commands.CityCommand.CitySetMayor)
                             .EndSub()
                             .BeginSub("invmsg")
                                 .WithDesc("Set city's invite msg.")
                                 .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_SET_ALL, EnumPlayerPermissions.CITY_SET_INV_MSG))
                                 .WithArgs(parsers.OptionalAll("invMsg"))
                                 .HandleWith(commands.CityCommand.CitySetInvMsg)
                             .EndSub()
                             .BeginSub("pvp")
                                 .WithDesc("Set pvp state.")
                                 .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_SET_ALL, EnumPlayerPermissions.CITY_SET_PVP))
                                 .WithArgs(parsers.WordRange("state", "on", "off"))
                                 .HandleWith(commands.CityCommand.CitySetPvP)
                             .EndSub()
                             .BeginSub("fire")
                                 .WithDesc("Set fire spread state.")
                                 .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_SET_ALL, EnumPlayerPermissions.CITY_SET_FIRE))
                                 .WithArgs(parsers.WordRange("state", "on", "off"))
                                 .HandleWith(commands.CityCommand.CitySetFire)
                             .EndSub()
                             .BeginSub("blast")
                                 .WithDesc("Set blast permission state.")
                                 .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_SET_ALL, EnumPlayerPermissions.CITY_SET_BLAST))
                                 .WithArgs(parsers.WordRange("state", "on", "off"))
                                 .HandleWith(commands.CityCommand.CitySetBlast)
                             .EndSub()
                             .BeginSub("title")
                                 .WithDesc("Set citizen's title.")
                                 .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_SET_ALL, EnumPlayerPermissions.CITY_SET_OTHERS_PREFIX))
                                 .HandleWith(commands.CityCommand.CitySetCitizenPrefix)
                                 .WithArgs(parsers.OptionalAll("playerName title"))
                             .EndSub()
                             .BeginSub("respawn")
                                 .WithDesc("Where to respawn: nearest, home (city temples) or camp (war camp).")
                                 .WithArgs(parsers.WordRange("mode", "nearest", "home", "camp"))
                                 .HandleWith(commands.CityCommand.SetRespawnPreference)
                             .EndSub()
                             .BeginSub("color")
                                 .WithArgs(parsers.Word("color"))
                                 .HandleWith(commands.CityCommand.CitySetPlotsColor)
                             .IgnoreAdditionalArgs()
                             .EndSub()
                             .BeginSub("colorint")
                                 .WithArgs(parsers.Word("colorint"))
                                 .HandleWith(commands.CityCommand.CitySetPlotsColorInt)
                             .IgnoreAdditionalArgs()
                             .EndSub()
                      .EndSub()
                      /////////
                      .BeginSub("invitesent")
                         .WithDesc("List all invitation city has sent.")
                          .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.SHOW_INVITES_SENT))
                         .HandleWith(commands.CityCommand.ShowInvitesSent)
                         .WithArgs(parsers.OptionalInt("page"))
                     .EndSub()
                      ////////
                     .BeginSub("rank")
                        .BeginSub("list")
                              .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_SHOW_RANK_OTHERS))
                             .HandleWith(commands.CityCommand.CityRankList)
                             .WithDesc("List player's ranks.")
                             .WithArgs(parsers.OptionalWord("playerName"))
                         .EndSub()
                         .BeginSub("add")
                             .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_SET_RANK))
                             .HandleWith(commands.CityCommand.CityRankAdd)
                             .WithDesc("Add rank to player.")
                             .WithArgs(parsers.Word("rank"), parsers.Word("playerName"))
                         .EndSub()
                         .BeginSub("remove")
                               .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_REMOVE_RANK))
                             .HandleWith(commands.CityCommand.CityRankRemove)
                             .WithDesc("Remove rank from player.")
                             .WithArgs(parsers.OptionalAll("rank playerName"))
                         .EndSub()
                         .BeginSub("create")
                              .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_CREATE_CITY_RANK))
                             .HandleWith(commands.CityCommand.CityRankCreateCustom)
                             .WithDesc("Create a new rank.")
                             .WithArgs(parsers.Word("rankName"))
                         .EndSub()
                         .BeginSub("delete")
                              .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_DELETE_CITY_RANK))
                             .HandleWith(commands.CityCommand.CityRankDeleteCustom)
                             .WithDesc("Create a new rank.")
                             .WithArgs(parsers.Word("rankName"))
                         .EndSub()
                         .BeginSub("addperm")
                              .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_ADD_PERMISSION_TO_RANK))
                             .HandleWith(commands.CityCommand.CityRankAddPermissions)
                             .WithDesc("Add permission to a rank.")
                             .WithArgs(parsers.Word("rankName"), parsers.All("permissions"))
                         .EndSub()
                         .BeginSub("removeperm")
                              .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_REMOVE_PERMISSION_FROM_RANK))
                             .HandleWith(commands.CityCommand.CityRankRemovePermissions)
                             .WithDesc("Add permission to a rank.")
                             .WithArgs(parsers.Word("rankName"), parsers.All("permissions"))
                         .EndSub()
                     .EndSub()
                     /////////
                     .BeginSub("join")
                         .HandleWith(commands.CityCommand.CityJoin)
                         .WithDesc("Join an open city.")
                         .WithArgs(parsers.Word("cityName"))
                     .EndSub()
                     /////////
                     .BeginSub("prison")
                         .BeginSub("list")
                             .WithDesc("List all prison cells in the city.")
                              .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_PRISON_ALL, EnumPlayerPermissions.CITY_PRISON_LIST))
                             .HandleWith(commands.CityCommand.PrisonList)
                         .EndSub()
                         .BeginSub("addcell")
                             .WithDesc("Add new cell in the prison plot.")
                             .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_PRISON_ALL, EnumPlayerPermissions.CITY_PRISON_ADD_CELL))
                             .HandleWith(commands.CityCommand.AddPrisonCell)
                         .EndSub()
                         .BeginSub("removecell")
                              .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_PRISON_ALL, EnumPlayerPermissions.CITY_PRISON_REMOVE_CELL))
                             .WithDesc("Remove prison cell by number.")
                             .HandleWith(commands.CityCommand.RemovePrisonCell)
                             .WithArgs(parsers.Int("prisonCellNumber"))
                         .EndSub()
                         .BeginSub("cremovecell")
                              .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_PRISON_ALL, EnumPlayerPermissions.CITY_PRISON_REMOVE_CELL))
                             .WithDesc("Remove prison cell by number.")
                             .HandleWith(commands.CityCommand.CRemovePrisonCell)
                             .WithArgs(parsers.Int("x"), parsers.Int("y"), parsers.Int("z"))
                         .EndSub()
                     .EndSub()
                         ////
                     .BeginSub("criminal")
                         .BeginSub("list")
                             .WithDesc("List all criminals for the city.")
                              .WithPreCondition((TextCommandCallingArgs args) => {
                                  if (args.Caller.Player is IServerPlayer player)
                                  {
                                      return TextCommandResult.Success();
                                      /*if (BaseCommand.CheckForPlayerPermissions(player, new EnumPlayerPermissions[] { }))
                                      {
                                          return TextCommandResult.Success();
                                      }
                                      else
                                      {
                                          return TextCommandResult.Error(Lang.Get("claims:you_dont_have_right_for_that_command"));
                                      }*/
                                  }
                                  return TextCommandResult.Error("");
                              })
                             .HandleWith(commands.CityCommand.CityCriminalList)
                         .EndSub()
                         .BeginSub("add")
                             .WithDesc("Mark selected player as criminal for the city.")
                             .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_ADD_CRIMINAL))
                             .WithArgs(parsers.Word("playerName"))
                             .HandleWith(commands.CityCommand.CityCriminalAdd)
                         .EndSub()
                         .BeginSub("remove")
                              .WithDesc("Remove player from criminals list for the city.")
                              .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_REMOVE_CRIMINAL))
                             .WithDesc("Remove prison cell by number.")
                             .HandleWith(commands.CityCommand.CityCriminalRemove)
                             .WithArgs(parsers.Word("playerName"))
                         .EndSub()
                     .EndSub()
                     .BeginSub("summon")
                         .BeginSub("list")
                             .WithDesc("List all summon points.")
                              .WithPreCondition((TextCommandCallingArgs args) => {
                                  if (args.Caller.Player is IServerPlayer player)
                                  {
                                      return TextCommandResult.Success();
                                     /* if (BaseCommand.CheckForPlayerPermissions(player, new EnumPlayerPermissions[] {  }))
                                      {
                                          return TextCommandResult.Success();
                                      }
                                      else
                                      {
                                          return TextCommandResult.Error(Lang.Get("claims:you_dont_have_right_for_that_command"));
                                      }*/
                                  }
                                  return TextCommandResult.Error("");
                              })
                             .HandleWith(commands.CityCommand.CitySummonList)
                         .EndSub()
                         .BeginSub("set")
                             .BeginSub("point")
                                 .WithDesc("Set summon point.")
                                 .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_SET_SUMMON))
                                 .HandleWith(commands.CityCommand.CitySummonSet)
                             .EndSub()
                             .BeginSub("name")
                                 .WithDesc("Set plot's summon point name.")
                                 .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_SET_SUMMON))
                                 .HandleWith(commands.CityCommand.CitySummonSetName)
                                 .WithArgs(parsers.Word("summonPointName"))
                            .EndSub()
                            .BeginSub("cname")
                                    .WithDesc("Set plot's summon point name by coords.")
                                    .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_SET_SUMMON))
                                    .HandleWith(commands.CityCommand.CitySummonSetNameByCoords)
                                    .WithArgs(parsers.OptionalVec3i("pointPos"), parsers.Word("summonPointName"))
                            .EndSub()
                         .EndSub()
                         .BeginSub("use")
                             .WithDesc("Try to teleport on summon point.")
                             .WithPreCondition((TextCommandCallingArgs args) => {
                                 if (args.Caller.Player is IServerPlayer player)
                                 {
                                     return TextCommandResult.Success();
                                     /*if (BaseCommand.CheckForPlayerPermissions(player, new EnumPlayerPermissions[] {  }))
                                     {
                                         return TextCommandResult.Success();
                                     }
                                     else
                                     {
                                         return TextCommandResult.Error(Lang.Get("claims:you_dont_have_right_for_that_command"));
                                     }*/
                                 }
                                 return TextCommandResult.Error("");
                             })
                             .WithArgs(parsers.Word("summonPointName"))
                             .HandleWith(commands.CityCommand.CitySummonTeleport)
                         .EndSub()
                     .EndSub()
                     .BeginSub("plotsgroup")
                        .WithAlias("pg")
                         .BeginSub("create")
                             .WithArgs(parsers.Word("groupName"))
                             .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_PLOTSGROUP_CREATE))
                             .HandleWith(commands.CityCommand.PlotsGroupCreate)
                             .WithDesc("Create new plotsgroup")
                         .EndSub()
                         .BeginSub("delete")
                             .HandleWith(commands.CityCommand.PlotsGroupDelete)
                              .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_PLOTSGROUP_REMOVE))
                             .WithDesc("Remove plotsgroup")
                             .WithArgs(parsers.Word("groupName"))
                         .EndSub()
                         .BeginSub("list")
                             .HandleWith(commands.CityCommand.PlotsGroupList)
                             .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_PLOTSGROUP_LIST))
                             .WithDesc("List plotsgroups")
                         .EndSub()
                         .BeginSub("listplayers")
                             .HandleWith(commands.CityCommand.PlotsGroupListPlayers)
                              .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_PLOTSGROUP_LIST))
                             .WithDesc("List players in the plotsgroup")
                             .WithArgs(parsers.Word("groupName"))
                         .EndSub()
                         .BeginSub("add")
                             .HandleWith(commands.CityCommand.PlotsGroupAddPlayerToGroup)
                              .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_PLOTSGROUP_ADD_PLAYER))
                             .WithDesc("Add player to the plotsgroup")
                             .WithArgs(parsers.Word("groupName"), parsers.Word("playerName"))
                         .EndSub()
                         .BeginSub("unadd")
                             .WithDesc("")
                             .HandleWith(commands.CityCommand.PlotsGroupUnaddTo)
                         .EndSub()
                         .BeginSub("kick")
                             .WithDesc("Kick player from the plotsgroup")
                             .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_PLOTSGROUP_KICK_PLAYER))
                             .HandleWith(commands.CityCommand.PlotsGroupKickPlayerFromGroup)
                             .WithArgs(parsers.Word("groupName"), parsers.Word ("playerName"))
                         .EndSub()
                         .BeginSub("plotadd")
                             .HandleWith(commands.CityCommand.PlotsGroupPlotAdd)
                             .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_PLOTSGROUP_ADD_PLOT))
                             .WithDesc("Add plot to the plotsgroup")
                             .WithArgs(parsers.Word("groupName"))
                         .EndSub()
                         .BeginSub("plotremove")
                             .HandleWith(commands.CityCommand.PlotsGroupPlotRemove)
                              .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_PLOTSGROUP_REMOVE_PLOT))
                             .WithDesc("Remove plot from the plotsgroup")
                             .WithArgs(parsers.Word("plotgroup"))
                         .EndSub()
                         .BeginSub("set")
                             .BeginSub("pvp")
                                .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_PLOTSGROUP_SET_PVP))
                               .HandleWith(commands.CityCommand.PlotsGroupSetPvp)
                               .WithDesc("Pvp state")
                               .WithArgs(parsers.Word("groupname"), parsers.WordRange("state", "on", "off"))
                           .EndSub()
                           .BeginSub("fire")
                               .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_PLOTSGROUP_SET_FIRE))
                               .HandleWith(commands.CityCommand.PlotsGroupSetFire)
                               .WithDesc("Firespread state")
                               .WithArgs(parsers.Word("groupname"), parsers.WordRange("state", "on", "off"))
                           .EndSub()
                           .BeginSub("blast")
                               .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_PLOTSGROUP_SET_BLAST))
                               .HandleWith(commands.CityCommand.PlotsGroupSetBlast)
                               .WithDesc("Blast state")
                               .WithArgs(parsers.Word("groupname"), parsers.WordRange("state", "on", "off"))
                           .EndSub()
                           .BeginSub("permissions")
                             .HandleWith(commands.CityCommand.PlotsGroupSet)
                             .WithAlias("p")
                             .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.CITY_PLOTSGROUP_SET))
                             .WithArgs(parsers.Word("groupname"),
                                       parsers.WordRange("permgroup", "citizen"),
                                       parsers.WordRange("permgroup", "build", "use", "attack"),
                                       parsers.WordRange("state", "on", "off"))
                         .EndSub()
                         .EndSub()
                      .EndSub()
                      // WAR (city-level conflict, no alliance required)
                      .BeginSub("war")
                        .WithAlias("w")
                          .BeginSub("declare")
                            .WithAlias("d")
                            .HandleWith(commands.CityCommand.DeclareCityConflict)
                            .WithDesc("Declare war on a city or alliance (only for cities without an alliance).")
                            .WithArgs(parsers.Word("cityOrAllianceName"))
                          .EndSub()
                          .BeginSub("revoke")
                            .WithAlias("r")
                            .HandleWith(commands.CityCommand.RevokeCityConflict)
                            .WithDesc("Revoke a pending war declaration.")
                            .WithArgs(parsers.Word("cityOrAllianceName"))
                          .EndSub()
                          .BeginSub("accept")
                            .WithAlias("a")
                            .HandleWith(commands.CityCommand.AcceptStartCityConflict)
                            .WithDesc("Accept an incoming war declaration.")
                            .WithArgs(parsers.Word("cityOrAllianceName"))
                          .EndSub()
                          .BeginSub("deny")
                            .HandleWith(commands.CityCommand.DenyStartCityConflict)
                            .WithDesc("Deny an incoming war declaration.")
                            .WithArgs(parsers.Word("cityOrAllianceName"))
                          .EndSub()
                          .BeginSub("offerstop")
                            .HandleWith(commands.CityCommand.OfferStopCityConflict)
                            .WithDesc("Offer to end an ongoing war.")
                            .WithArgs(parsers.Word("cityOrAllianceName"))
                          .EndSub()
                          .BeginSub("acceptstop")
                            .HandleWith(commands.CityCommand.AcceptStopCityConflict)
                            .WithDesc("Accept the offer to stop a war.")
                            .WithArgs(parsers.Word("cityOrAllianceName"))
                          .EndSub()
                          .BeginSub("denystop")
                            .HandleWith(commands.CityCommand.DenyStopCityConflict)
                            .WithDesc("Deny the offer to stop a war.")
                            .WithArgs(parsers.Word("cityOrAllianceName"))
                          .EndSub()
                          .BeginSub("offerpeace")
                            .HandleWith(commands.CityCommand.OfferPeaceCityConflict)
                            .WithDesc("Offer peace with terms: none / reparations <amount> / vassalage / cession (stand on the enemy plot).")
                            .WithArgs(parsers.Word("cityOrAllianceName"), parsers.WordRange("term", "none", "reparations", "vassalage", "cession"), parsers.OptionalInt("amount"))
                          .EndSub()
                          .BeginSub("vassals")
                            .HandleWith(commands.CityCommand.VassalsInfo)
                            .WithDesc("Show your overlord and your vassals.")
                          .EndSub()
                          .BeginSub("rebel")
                            .HandleWith(commands.CityCommand.Rebel)
                            .WithDesc("Break free from your overlord (gives them a casus belli).")
                          .EndSub()
                          .BeginSub("cb")
                            .HandleWith(commands.CityCommand.CasusBelliInfo)
                            .WithDesc("List whom you currently have a casus belli against.")
                          .EndSub()
                          .BeginSub("nap")
                            .BeginSub("offer")
                              .HandleWith(commands.CityCommand.NapOffer)
                              .WithDesc("Offer a non-aggression pact (optionally for N days).")
                              .WithArgs(parsers.Word("cityOrAllianceName"), parsers.OptionalInt("days"))
                            .EndSub()
                            .BeginSub("accept")
                              .HandleWith(commands.CityCommand.NapAccept)
                              .WithDesc("Accept a non-aggression pact offer.")
                              .WithArgs(parsers.Word("cityOrAllianceName"))
                            .EndSub()
                            .BeginSub("deny")
                              .HandleWith(commands.CityCommand.NapDeny)
                              .WithDesc("Deny a non-aggression pact offer.")
                              .WithArgs(parsers.Word("cityOrAllianceName"))
                            .EndSub()
                            .BeginSub("list")
                              .HandleWith(commands.CityCommand.NapList)
                              .WithDesc("List your active non-aggression pacts.")
                            .EndSub()
                            .BeginSub("break")
                              .HandleWith(commands.CityCommand.NapBreak)
                              .WithDesc("Break a pact early (pays a penalty, gives them a casus belli).")
                              .WithArgs(parsers.Word("cityOrAllianceName"))
                            .EndSub()
                          .EndSub()
                          .BeginSub("ultimatum")
                            .BeginSub("offer")
                              .HandleWith(commands.CityCommand.UltimatumOffer)
                              .WithDesc("Demand money or the plot you stand on; refusal grants a free, justified war.")
                              .WithArgs(parsers.Word("cityOrAllianceName"), parsers.Word("money|plot"), parsers.OptionalInt("amount"))
                            .EndSub()
                            .BeginSub("accept")
                              .HandleWith(commands.CityCommand.UltimatumAccept)
                              .WithDesc("Comply with an ultimatum (pay / cede the plot).")
                              .WithArgs(parsers.Word("cityOrAllianceName"))
                            .EndSub()
                            .BeginSub("deny")
                              .HandleWith(commands.CityCommand.UltimatumDeny)
                              .WithDesc("Refuse an ultimatum (gives them a casus belli against you).")
                              .WithArgs(parsers.Word("cityOrAllianceName"))
                            .EndSub()
                            .BeginSub("list")
                              .HandleWith(commands.CityCommand.UltimatumList)
                              .WithDesc("List the free-war justifications you hold from refused ultimatums.")
                            .EndSub()
                          .EndSub()
                          .BeginSub("cession")
                            .BeginSub("accept")
                              .HandleWith(commands.CityCommand.CessionAccept)
                              .WithDesc("Confirm ceding your city's plot demanded from your alliance.")
                              .WithArgs(parsers.Word("cityOrAllianceName"))
                            .EndSub()
                            .BeginSub("deny")
                              .HandleWith(commands.CityCommand.CessionDeny)
                              .WithDesc("Refuse to cede your city's plot (cancels the peace/ultimatum).")
                              .WithArgs(parsers.Word("cityOrAllianceName"))
                            .EndSub()
                          .EndSub()
                          .BeginSub("claimcamp")
                            .HandleWith(commands.CityCommand.ClaimCamp)
                            .WithDesc("Claim a war camp on the free plot you stand on during an active battle.")
                          .EndSub()
                          .BeginSub("unclaimcamp")
                            .HandleWith(commands.CityCommand.UnclaimCamp)
                            .WithDesc("Remove the war camp you stand on.")
                          .EndSub()
                          .BeginSub("camptp")
                            .HandleWith(commands.CityCommand.CampTeleport)
                            .WithDesc("Teleport to your city's war camp. Channelled, moving cancels it, then goes on cooldown.")
                          .EndSub()
                          .BeginSub("bounty")
                            .BeginSub("place")
                              .HandleWith(commands.CityCommand.BountyPlace)
                              .WithDesc("Place a bounty on a player's head.")
                              .WithArgs(parsers.Word("playerName"), parsers.Int("amount"))
                            .EndSub()
                            .BeginSub("cancel")
                              .HandleWith(commands.CityCommand.BountyCancel)
                              .WithDesc("Cancel your bounty on a player and get a refund.")
                              .WithArgs(parsers.Word("playerName"))
                            .EndSub()
                            .BeginSub("list")
                              .HandleWith(commands.CityCommand.BountyList)
                              .WithDesc("Show the bounty on a player's head.")
                              .WithArgs(parsers.Word("playerName"))
                            .EndSub()
                          .EndSub()
                      .EndSub();
        }
        public static void RegisterAllianceCommands(CommandArgumentParsers parsers, ICoreServerAPI sapi)
        {
            sapi.ChatCommands.Create("alliance")
                .RequiresPlayer().RequiresPrivilege(Privilege.chat).WithAlias("a")
                        /////////
                      .BeginSub("conflict")
                        .WithAlias("c")
                          .BeginSub("declare")
                            .WithAlias("d")
                            .HandleWith(commands.AllianceCommand.DeclareConflict)
                            .WithDesc("Try to start a conflict with an alliance.")
                            .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.ALLIANCE_DECLARE_CONFLICT))
                            .WithArgs(parsers.Word("allianceName"))
                         .EndSub()
                         .BeginSub("revoke")
                            .WithAlias("r")
                            .HandleWith(commands.AllianceCommand.RevokeConflict)
                            .WithDesc("Remove declaration if it's not accepted yet.")
                            .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.ALLIANCE_REVOKE_CONFLICT))
                            .WithArgs(parsers.Word("allianceName"))
                         .EndSub()
                         .BeginSub("accept")
                            .WithAlias("a")
                            .HandleWith(commands.AllianceCommand.AcceptStartConflict)
                            .WithDesc("Accept to start a conflict.")
                            .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.ALLIANCE_ACCEPT_CONFLICT))
                            .WithArgs(parsers.Word("allianceName"))
                         .EndSub()
                         .BeginSub("deny")
                            .HandleWith(commands.AllianceCommand.DenyStartConflict)
                            .WithDesc("Deny to start a conflict.")
                            .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.ALLIANCE_DENY_CONFLICT))
                            .WithArgs(parsers.Word("allianceName"))
                         .EndSub()
                         .BeginSub("offerstop")
                            .HandleWith(commands.AllianceCommand.OfferStopConflict)
                            .WithDesc("Offer to stop a conflict, optionally with peace terms: none / reparations <amount> / vassalage.")
                            .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.ALLIANCE_OFFER_STOP_CONFLICT))
                            .WithArgs(parsers.Word("allianceName"), parsers.OptionalWord("term"), parsers.OptionalInt("amount"))
                         .EndSub()
                         .BeginSub("acceptstop")
                            .HandleWith(commands.AllianceCommand.AcceptStopConflict)
                            .WithDesc("Accept to stop a conflict.")
                            .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.ALLIANCE_ACCEPT_STOP_CONFLICT))
                            .WithArgs(parsers.Word("allianceName"))
                         .EndSub()
                         .BeginSub("denystop")
                            .HandleWith(commands.AllianceCommand.DenyStopConflict)
                            .WithDesc("Deny to stop a conflict.")
                            .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.ALLIANCE_DENY_STOP_CONFLICT))
                            .WithArgs(parsers.Word("allianceName"))
                         .EndSub()
                         .BeginSub("cb")
                            .HandleWith(commands.CityCommand.CasusBelliInfo)
                            .WithDesc("List whom your alliance currently has a casus belli against.")
                         .EndSub()
                         // NAP + ultimatum share the party-aware CityCommand handlers (they resolve alliance-vs-city from the caller).
                         .BeginSub("nap")
                            .BeginSub("offer")
                              .HandleWith(commands.CityCommand.NapOffer)
                              .WithDesc("Offer a non-aggression pact (optionally for N days).")
                              .WithArgs(parsers.Word("cityOrAllianceName"), parsers.OptionalInt("days"))
                            .EndSub()
                            .BeginSub("accept")
                              .HandleWith(commands.CityCommand.NapAccept)
                              .WithDesc("Accept a non-aggression pact offer.")
                              .WithArgs(parsers.Word("cityOrAllianceName"))
                            .EndSub()
                            .BeginSub("deny")
                              .HandleWith(commands.CityCommand.NapDeny)
                              .WithDesc("Deny a non-aggression pact offer.")
                              .WithArgs(parsers.Word("cityOrAllianceName"))
                            .EndSub()
                            .BeginSub("list")
                              .HandleWith(commands.CityCommand.NapList)
                              .WithDesc("List your active non-aggression pacts.")
                            .EndSub()
                            .BeginSub("break")
                              .HandleWith(commands.CityCommand.NapBreak)
                              .WithDesc("Break a pact early (pays a penalty, gives them a casus belli).")
                              .WithArgs(parsers.Word("cityOrAllianceName"))
                            .EndSub()
                         .EndSub()
                         .BeginSub("ultimatum")
                            .BeginSub("offer")
                              .HandleWith(commands.CityCommand.UltimatumOffer)
                              .WithDesc("Demand money or the plot you stand on; refusal grants a free, justified war.")
                              .WithArgs(parsers.Word("cityOrAllianceName"), parsers.Word("money|plot"), parsers.OptionalInt("amount"))
                            .EndSub()
                            .BeginSub("accept")
                              .HandleWith(commands.CityCommand.UltimatumAccept)
                              .WithDesc("Comply with an ultimatum (pay / cede the plot).")
                              .WithArgs(parsers.Word("cityOrAllianceName"))
                            .EndSub()
                            .BeginSub("deny")
                              .HandleWith(commands.CityCommand.UltimatumDeny)
                              .WithDesc("Refuse an ultimatum (gives them a casus belli against you).")
                              .WithArgs(parsers.Word("cityOrAllianceName"))
                            .EndSub()
                            .BeginSub("list")
                              .HandleWith(commands.CityCommand.UltimatumList)
                              .WithDesc("List the free-war justifications you hold from refused ultimatums.")
                            .EndSub()
                         .EndSub()
                     .EndSub()
                     .BeginSub("create")
                        .HandleWith(commands.AllianceCommand.CreateAlliance)
                        .WithAlias("new")
                        .WithDesc("Create a new alliance.")
                        .WithArgs(parsers.Word("allianceName"))
                     .EndSub()
                     .BeginSub("delete")
                        .HandleWith(commands.AllianceCommand.DeleteAlliance)
                        .WithAlias("remove")
                        .WithDesc("Delete an alliance.")
                     .EndSub()
                     .BeginSub("leave")
                        .HandleWith(commands.AllianceCommand.LeaveAlliance)
                        .WithAlias("l")
                        .WithDesc("Leave from an alliance.")
                     .EndSub()
                     .BeginSub("kick")
                        .HandleWith(commands.AllianceCommand.KickFromAlliance)
                        .WithDesc("Kick a city from an alliance.")
                        .WithArgs(parsers.Word("cityName"))
                     .EndSub()
                     .BeginSub("invite")
                        .HandleWith(commands.AllianceCommand.InviteToAlliance)
                        .WithDesc("Invite a city to an alliance.")
                        .WithArgs(parsers.Word("cityName"))
                     .EndSub()
                     .BeginSub("listinvites")
                        .HandleWith(commands.AllianceCommand.PrintInviteList)
                        .WithDesc("List all invites from the alliance.")
                        .WithArgs(parsers.OptionalInt("pageNumber"))
                     .EndSub()
                     .BeginSub("set")
                        .BeginSub("name")
                            .HandleWith(commands.AllianceCommand.SetNameAlliance)
                            .WithDesc("Change name of the alliance.")
                            .WithArgs(parsers.Word("newName"))
                        .EndSub()
                        .BeginSub("fee")
                            .HandleWith(commands.AllianceCommand.SetFeeAlliance)
                            .WithDesc("Set fee of the alliance.")
                            .WithArgs(parsers.Int("number"))
                        .EndSub()
                        .BeginSub("capital")
                            .HandleWith(commands.AllianceCommand.SetCapitalAlliance)
                            .WithDesc("Set capital of the alliance.")
                            .WithArgs(parsers.Word("cityName"))
                        .EndSub()
                        .BeginSub("prefix")
                            .HandleWith(commands.AllianceCommand.SetPrefixAlliance)
                            .WithDesc("Set prefix string.")
                            .WithArgs(parsers.OptionalWord("string"))
                        .EndSub()
                     .EndSub()
                     .BeginSub("union")
                         .BeginSub("declare")
                            .WithAlias("d")
                            .HandleWith(commands.AllianceCommand.DeclareUnion)
                             .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.ALLIANCE_DECLARE_UNION))
                            .WithDesc("Send letter to be allies with the second alliance.")
                            .WithArgs(parsers.Word("allianceName"))
                         .EndSub()
                         .BeginSub("revoke")
                            .WithAlias("r")
                            .HandleWith(commands.AllianceCommand.RevokeUnion)
                            .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.ALLIANCE_REVOKE_UNION))
                            .WithDesc("Denounce the union: announced now, takes effect after a delay.")
                            .WithArgs(parsers.Word("allianceName"))
                         .EndSub()
                         .BeginSub("cancelbreak")
                            .HandleWith(commands.AllianceCommand.CancelUnionBreak)
                            .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.ALLIANCE_REVOKE_UNION))
                            .WithDesc("Call off an announced union break before it takes effect.")
                            .WithArgs(parsers.Word("allianceName"))
                         .EndSub()
                         .BeginSub("dissolve")
                            .HandleWith(commands.AllianceCommand.DissolveUnion)
                            .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.ALLIANCE_REVOKE_UNION))
                            .WithDesc("Offer to dissolve the union by mutual consent (no delay, no cooldowns).")
                            .WithArgs(parsers.Word("allianceName"))
                         .EndSub()
                         .BeginSub("decline")
                            .WithAlias("dn")
                            .HandleWith(commands.AllianceCommand.UnsendInviteUnion)
                            .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.ALLIANCE_DENY_UNION))
                            .WithDesc("Decline letter to be allies with the second alliance.")
                            .WithArgs(parsers.Word("allianceName"))
                         .EndSub()
                         .BeginSub("accept")
                            .WithAlias("ac")
                            .HandleWith(commands.AllianceCommand.AcceptInviteUnion)
                            .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.ALLIANCE_ACCEPT_UNION))
                            .WithDesc("Accept letter to be allies with the second alliance.")
                            .WithArgs(parsers.Word("allianceName"))
                         .EndSub()
                     ;
                     
        }
        public static void RegisterCitizenCommands(CommandArgumentParsers parsers, ICoreServerAPI sapi)
        {
            sapi.ChatCommands.Create("citizen")
                  .WithAlias("ci")
                  .RequiresPrivilege(Privilege.chat)
                  .BeginSub("info")
                       .HandleWith(commands.CitizenCommand.CitizenInfo)
                       .WithArgs(parsers.Word("playerName"))
                       .WithDesc("Print info about selected player.")
                   .EndSub()
                   /////////
                    .BeginSub("prices")
                       .HandleWith(commands.CitizenCommand.CitizenPrices)
                       .WithDesc("List prices.")
                   .EndSub()
                    /////////
                    .BeginSub("nextdaytimer")
                       .WithAlias("ndt")
                       .HandleWith(commands.CitizenCommand.NextDayTimer)
                       .WithDesc("Show time until a next mod's day.")
                   .EndSub()
                    /////////
                    .BeginSub("invitelist")
                       .HandleWith(commands.CitizenCommand.InvitesList)
                       .WithDesc("List all invites to cities you got.")
                       .WithArgs(parsers.OptionalInt("pageNumber"))
                   .EndSub()
                    /////////
                    .BeginSub("friend")
                       .BeginSub("info")
                           .HandleWith(commands.CitizenCommand.FriendsList)
                           .WithDesc("Show list of friends")
                       .EndSub()
                       .BeginSub("add")
                           .HandleWith(commands.CitizenCommand.FriendAdd)
                           .WithDesc("Add new friend")
                           .WithArgs(parsers.Word("playerName"))
                       .EndSub()
                       .BeginSub("remove")
                           .HandleWith(commands.CitizenCommand.FriendRemove)
                           .WithDesc("Remove friend")
                           .WithArgs(parsers.Word("playerName"))
                       .EndSub()
                   .EndSub()
                   /////////
                   
                   ;
            /*sapi.ChatCommands.Create("citizen")
                  .RequiresPrivilege(Privilege.chat)
                   .BeginSub("fees")
                       .HandleWith(commands.CitizenCommand.processFee)
                       .WithDesc("Show fee state.")
                       .WithAlias("feeState")
                   .EndSub()

                   .BeginSub("prices")
                       .HandleWith(commands.CitizenCommand.processCitizenPrices)
                       .WithDesc("Prices list")
                   .EndSub()
                   .BeginSub("prison")
                       .BeginSub("info")
                           .HandleWith(commands.CitizenCommand.prisonInfo)
                           .WithDesc("Show prison prices")
                       .EndSub()
                       .BeginSub("payout")
                           .HandleWith(commands.CitizenCommand.processPrisonPayout)
                           .WithDesc("Prison handle")
                       .EndSub()
                   .EndSub()
                  
                   .BeginSub("set")
                       .BeginSub("info")
                           .HandleWith(commands.CitizenCommand.citizenSetInfo)
                           .WithDesc("Show player's perms for friends")
                       .EndSub()
                       .BeginSub("permissions")
                           .WithAlias("p")
                           .HandleWith(commands.CitizenCommand.SetPerm)
                           .WithArgs(parsers.All("permGroup permType on/off"))
                       .EndSub()
                   .EndSub();*/
        }
        public static void RegisterPlotCommands(CommandArgumentParsers parsers, ICoreServerAPI sapi)
        {
            sapi.ChatCommands.Create("plot")
               .RequiresPrivilege(Privilege.chat)
                   .BeginSub("here")
                       .HandleWith(commands.PlotCommand.HereInfo)
                       .WithDesc("List info about plot you stand on.")
                   .EndSub()
                   /////////
                   .BeginSub("borders")
                       .WithArgs(parsers.WordRange("on/off", "on", "off"))
                       .WithDesc("Select borders of plot you currently stand in.")
                       .HandleWith(commands.PlotCommand.plotBorders)
                   .EndSub()
                   /////////
                   .BeginSub("claim")
                       .HandleWith(commands.PlotCommand.PlotClaim)
                       .WithDesc("Buy plot you current stand on.(Ownership by a player)")
                   .EndSub()
                   /////////
                   .BeginSub("unclaim")
                       .HandleWith(commands.PlotCommand.PlotUnclaim)
                       .WithDesc("Unclaim plot you stand on.(Remove ownership)")
                   .EndSub()
                    /////////
                    .BeginSub("set")
                       .BeginSub("permissions")
                           .WithAlias("p")
                           .HandleWith(commands.PlotCommand.SetPermissions)
                           .WithDesc("Set plot permissions")
                           .IgnoreAdditionalArgs()
                       .EndSub()
                       .BeginSub("pvp")
                            .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.PLOT_SET_ALL_CITY_PLOTS, EnumPlayerPermissions.PLOT_SET_PVP))
                           .HandleWith(commands.PlotCommand.SetPvp)
                           .WithDesc("Pvp state")
                           .WithArgs(parsers.WordRange("state", "on", "off"))
                       .EndSub()
                       .BeginSub("fire")
                           .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.PLOT_SET_ALL_CITY_PLOTS, EnumPlayerPermissions.PLOT_SET_FIRE))
                           .HandleWith(commands.PlotCommand.SetFire)
                           .WithDesc("Firespread state")
                           .WithArgs(parsers.WordRange("state", "on", "off"))
                       .EndSub()
                       .BeginSub("blast")
                           .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.PLOT_SET_ALL_CITY_PLOTS, EnumPlayerPermissions.PLOT_SET_BLAST))
                           .HandleWith(commands.PlotCommand.SetBlast)
                           .WithDesc("Blast state")
                           .WithArgs(parsers.WordRange("state", "on", "off"))
                       .EndSub()
                       .BeginSub("name")
                           .HandleWith(commands.PlotCommand.SetName)
                           .WithDesc("Set plot's name")
                           .WithArgs(parsers.Word("plotName"))
                       .EndSub()
                       .BeginSub("fee")
                           .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.PLOT_SET_ALL_CITY_PLOTS, EnumPlayerPermissions.PLOT_SET_FEE))
                           .HandleWith(commands.PlotCommand.SetFee)
                           .WithDesc("Set plot fee")
                           .WithArgs(parsers.Int("fee"))
                       .EndSub()
                       .BeginSub("type")
                            .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.PLOT_SET_ALL_CITY_PLOTS, EnumPlayerPermissions.PLOT_SET_TYPE))
                           .HandleWith(commands.PlotCommand.SetType)
                           .WithDesc("Set plot type")
                           .WithArgs(parsers.Word("plotType"))
                       .EndSub()
               .EndSub()
               /////////
               .BeginSub("fs")
                    .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.PLOT_SET_ALL_CITY_PLOTS, EnumPlayerPermissions.PLOT_SET_FS))
                   .HandleWith(commands.PlotCommand.SetForSale)
                   .WithArgs(parsers.Int("price"))
                   .WithDesc("Set plot for sale")
                   .WithAlias("forsale")
               .EndSub()
                /////////
                .BeginSub("nfs")
                .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequirePermission(args, EnumPlayerPermissions.PLOT_SET_ALL_CITY_PLOTS, EnumPlayerPermissions.PLOT_SET_NFS))
                   .HandleWith(commands.PlotCommand.SetNotForSale)
                   .WithDesc("Remove plot from sale")
                   .WithAlias("notforsale")
               .EndSub()
                   ;

            /*              
               .BeginSub("innerclaim")
                   .IgnoreAdditionalArgs()
                   .HandleWith(commands.plotCommand.processInnerClaim)
               .EndSub()
               .BeginSub("plotmsgs")
                   .WithArgs(parsers.WordRange("state", "0", "1", "2", "3"))
                   .WithDesc("Show nothing - 0, only msgs - 1, only hud - 2, both - 3")
                   .HandleWith(commands.plotCommand.plotMsgs)
               .EndSub()
              
               ;*/
        }
        public static void RegisterCAdminCommands(CommandArgumentParsers parsers, ICoreServerAPI sapi)
        {
            sapi.ChatCommands.Create("cadmin")
                .RequiresPlayer().RequiresPrivilege(Privilege.controlserver)
                .BeginSub("nday")
                     .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                    .HandleWith(commands.CAdminCommand.triggerNextDay)
                    .WithDesc("Trigger new day events")
                .EndSub()
                .BeginSub("nhour")
                     .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                    .HandleWith(commands.CAdminCommand.triggerNextHour)
                    .WithDesc("Trigger new hour events")
                .EndSub()
                .BeginSub("diag")
                    .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                    .HandleWith(commands.CAdminCommand.DiagPlayer)
                    .WithDesc("Diagnose player perms/city/mayor state")
                    .WithArgs(parsers.Word("playerName"))
                .EndSub()
                .BeginSub("plot")
                    .BeginSub("set")
                       .BeginSub("permissions")
                             .WithAlias("p")
                               .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                             .WithArgs(parsers.Word("group"), parsers.Word("permType"), parsers.WordRange("state", "on", "off"))
                             .HandleWith(commands.CAdminCommand.plotPermissions)
                        .EndSub()
                        .BeginSub("pvp")
                             .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                            .HandleWith(commands.CAdminCommand.plotPvp)
                            .WithDesc("Pvp state")
                            .WithArgs(parsers.WordRange("state", "on", "off"))
                        .EndSub()
                        .BeginSub("blast")
                             .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                            .HandleWith(commands.CAdminCommand.plotBlast)
                            .WithDesc("Blast state")
                            .WithArgs(parsers.WordRange("state", "on", "off"))
                        .EndSub()
                        .BeginSub("fire")
                             .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                            .HandleWith(commands.CAdminCommand.plotFire)
                            .WithDesc("Fire state")
                            .WithArgs(parsers.WordRange("state", "on", "off"))
                        .EndSub()
                    .EndSub()
                    .BeginSub("type")
                        .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                        .HandleWith(commands.CAdminCommand.plotType)
                        .WithArgs(parsers.Word("type"))
                    .EndSub()
                    .BeginSub("fee")
                        .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                        .HandleWith(commands.CAdminCommand.plotFee)
                        .WithArgs(parsers.Int("fee"))
                    .EndSub()
                    .BeginSub("fs")
                         .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                        .HandleWith(commands.CAdminCommand.plotForSale)
                        .WithArgs(parsers.Int("price"))
                    .EndSub()
                .EndSub()
                .BeginSub("city")
                    .BeginSub("new")
                         .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                        .HandleWith(commands.CAdminCommand.cCreateCity)
                        .WithArgs(parsers.Word("cityName"))
                        .WithDesc("New city creation")
                    .EndSub()
                    .BeginSub("delete")
                        .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                        .HandleWith(commands.CAdminCommand.cityDelete)
                        .WithDesc("City remove")
                        .WithArgs(parsers.Word("cityName"))
                    .EndSub()
                    .BeginSub("claim")
                        .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                        .HandleWith(commands.CAdminCommand.cityClaim)
                        .WithDesc("Claim plot for city")
                        .WithArgs(parsers.Word("cityName"))
                    .EndSub()
                    .BeginSub("radiusclaim")
                        .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                        .HandleWith(commands.CAdminCommand.cityRadiusClaim)
                        .WithDesc("Claim plot for city in radius")
                        .WithArgs(parsers.Word("cityName"), parsers.Int("radius"))
                    .EndSub()
                    .BeginSub("unclaim")
                         .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                        .HandleWith(commands.CAdminCommand.cityUnclaim)
                        .WithDesc("Unclaim city plot")
                        .WithArgs(parsers.Word("cityName"))
                    .EndSub()
                    .BeginSub("kick")
                          .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                        .HandleWith(commands.CAdminCommand.cCityPlayerKick)
                        .WithDesc("Kick player from city")
                        .WithArgs(parsers.Word("cityName"), parsers.Word("playerName"))
                        .IgnoreAdditionalArgs()
                    .EndSub()
                    .BeginSub("add")
                          .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                        .HandleWith(commands.CAdminCommand.cCityPlayerAdd)
                        .WithArgs(parsers.Word("cityName"), parsers.Word("playerName"))
                        .WithDesc("Add player to the city")
                        .IgnoreAdditionalArgs()
                    .EndSub()
                    .BeginSub("set")
                        .BeginSub("name")
                            .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                            .HandleWith(commands.CAdminCommand.cCitySetName)
                            .WithArgs(parsers.Word("cityName"), parsers.Word("newName"))
                        .EndSub()
                        .BeginSub("pvp")
                            .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                            .HandleWith(commands.CAdminCommand.citySetPvp)
                            .WithArgs(parsers.Word("cityName"), parsers.Word("state"))
                        .EndSub()
                        .BeginSub("fire")
                            .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                            .HandleWith(commands.CAdminCommand.citySetFire)
                            .WithArgs(parsers.Word("cityName"), parsers.Word("state"))
                        .EndSub()
                        .BeginSub("blast")
                            .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                            .HandleWith(commands.CAdminCommand.citySetBlast)
                            .WithArgs(parsers.Word("cityName"), parsers.Word("state"))
                        .EndSub()
                        .BeginSub("open")
                            .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                            .HandleWith(commands.CAdminCommand.citySetOpenClosed)
                            .WithArgs(parsers.Word("cityName"), parsers.Word("state"))
                        .EndSub()
                        .BeginSub("technical")
                             .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                            .HandleWith(commands.CAdminCommand.citySetTechnical)
                            .WithArgs(parsers.Word("cityName"), parsers.Word("state"))
                        .EndSub()
                        .BeginSub("fee")
                             .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                            .HandleWith(commands.CAdminCommand.citySetFee)
                            .WithArgs(parsers.Word("cityName"), parsers.Int("fee"))
                        .EndSub()
                        .BeginSub("mayor")
                             .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                            .HandleWith(commands.CAdminCommand.citySetMayor)
                            .WithArgs(parsers.Word("cityName"), parsers.Word("newMayorName"))
                        .EndSub()
                        .BeginSub("bonusclaims")
                             .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                            .HandleWith(commands.CAdminCommand.citySetBonusPlots)
                            .WithArgs(parsers.Word("cityName"), parsers.Int("bonusClaimAmount"))
                        .EndSub()
                    .EndSub()
                .EndSub()
                /*.BeginSub("claimscolor")
                    .HandleWith(commands.CAdminCommand.processClaimsColor)
                    .IgnoreAdditionalArgs()
                .EndSub()*/
                .BeginSub("world")
                    .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                        .BeginSub("info")
                             .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                            .HandleWith(commands.CAdminCommand.worldInfo)
                        .EndSub()
                        .BeginSub("set")
                             .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                             .WithArgs(parsers.WordRange("param", "blastew", "pvpew", "fireew", "pvpfb", "firefb", "blastfb"), parsers.WordRange("state", "on", "off"))
                            .HandleWith(commands.CAdminCommand.worldSet)
                        .EndSub()
                //.HandleWith(commands.CAdminCommand.cWorldCommands)
                //.IgnoreAdditionalArgs()
                .EndSub()
                /*.BeginSub("gb")
                    .HandleWith(commands.CAdminCommand.cGlobalBank)
                    .IgnoreAdditionalArgs()
                .EndSub()*/
                .BeginSub("backup")
                    .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                    .HandleWith(commands.CAdminCommand.processBackup)
                .EndSub()
                .BeginSub("startwar")
                    .WithArgs(parsers.Word("firstParty"), parsers.Word("secondParty"))
                    .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                    .HandleWith(commands.CAdminCommand.StartWarTime)
                .EndSub()
                .BeginSub("setbattledate")
                    .WithArgs(parsers.Word("firstParty"), parsers.Word("secondParty"), parsers.OptionalInt("minutesUntilStart"), parsers.OptionalInt("battleDurationMinutes"))
                    .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                    .HandleWith(commands.CAdminCommand.SetBattleDate)
                .EndSub()
                .BeginSub("endwar")
                    .WithArgs(parsers.Word("firstParty"), parsers.Word("secondParty"))
                    .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                    .HandleWith(commands.CAdminCommand.EndWar)
                .EndSub()
                .BeginSub("setcfg")
                    .WithArgs(parsers.Word("key"), parsers.Word("value"))
                    .WithPreCondition((TextCommandCallingArgs args) => BaseCommand.RequireAdminRole(args))
                    .HandleWith(commands.CAdminCommand.setCfg)
                .EndSub()
                ;
        }            
    }
}
