namespace claims.src.gui.prettyGui
{
    public enum EnumSecondaryWindowTab
    {
        NONE, NEED_NAME, NEED_AGREE, INVITE_TO_CITY_NEED_NAME, KICK_FROM_CITY_NEED_NAME, UNINVITE_TO_CITY,
        CLAIM_CITY_PLOT_CONFIRM, UNCLAIM_CITY_PLOT_CONFIRM, PLOT_PERMISSIONS, ADD_FRIEND_NEED_NAME, REMOVE_FRIEND,
        PLOT_SET_PRICE_NEED_NUMBER, PLOT_SET_TAX, PLOT_SET_TYPE, PLOT_SET_NAME, PLOT_CLAIM, PLOT_UNCLAIM,
        CITY_TITLE_SELECT_CITIZEN, CITY_TITLE_CITIZEN_SELECTED, LEAVE_CITY_CONFIRM,
        CITY_RANK_REMOVE_CONFIRM, CITY_RANK_ADD, SELECT_NEW_CITY_NAME, ADD_CRIMINAL_NEED_NAME, REMOVE_CRIMINAL,
        CITY_PRISON_REMOVE_CELL_CONFIRM, CITY_SUMMON_NEED_NAME, ADD_PLOTSGROUP_MEMBER_NEED_NAME, REMOVE_PLOTSGROUP_MEMBER_SELECT,
        REMOVE_PLOTSGROUP_MEMBER_CONFIRM,
        CITY_PLOTSGROUP_PERMISSIONS, CITY_PLOTSGROUP_PLOT_CLAIM_CONFIRM, CITY_PLOTSGROUP_PLOT_UNCLAIM_CONFIRM,
        CITY_PLOTSGROUP_ADD_NEW_NEED_NAME, CITY_PLOTSGROUP_REMOVE_SELECT, CITY_PLOTSGROUP_REMOVE_CONFIRM,

        SELECT_NEW_ALLIANCE_NAME, INVITE_TO_ALLIANCE_NEED_NAME, KICK_FROM_ALLIANCE_NEED_NAME, UNINVITE_TO_ALLIANCE,
        LEAVE_ALLIANCE_CONFIRM, NEW_ALLIANCE_NEED_NAME, ALLIANCE_PREFIX_NEED_NAME, ALLIANCE_SEND_NEW_CONFLICT_LETTER_NEED_NAME,
        ALLIANCE_SEND_PEACE_OFFER_CONFIRM,
        CITY_PLOTS_PERMISSIONS, CITY_RANK_DELETE_CONFIRM, CITY_RANK_CREATION_NEED_NAME,
        ALLIANCE_SEND_NEW_UNION_LETTER_NEED_NAME, ALLIANCE_CANCEL_UNION_SELECT,
        CITY_SEND_NEW_CONFLICT_LETTER_NEED_NAME
    }
}
