using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace claims.src.network.packets
{
    public enum PacketsContentEnum
    {
        ON_JOIN, ENTER_ZONE, ADD_SINGLE_PLOT, REMOVE_SINGLE_PLOT, ALL_CITY_COLORS, CLIENT_INFORM_ZONES_TIMESTAMPS,
        SERVER_UPDATED_ZONES_ANSWER, SERVER_REMOVE_COLLECTED_PLOTS, SERVER_UPDATE_COLLECTED_PLOTS, CITY_CITIZENS_RANKS_REQUEST,

        OWN_CITY_DELETED, AGREE_NEEDED_ON_NEW_CITY_CREATION, OWN_CITY_INFO_ON_JOIN, OWN_NEW_CITY_CREATED,
        ON_CITY_JOINED, ON_KICKED_FROM_CITY,
        ON_SOME_CITY_PARAMS_UPDATED,

        CURRENT_PLOT_INFO, CURRENT_PLOT_CLIENT_REQUEST
    }
}
